/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.Gestion_cabalo;
import Persistencia.ConexionBD;
import java.sql.Connection;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author carvi
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
private final Connection conexion; 

    public Pantalla() {
        initComponents();
        this.setLocationRelativeTo(null);
        conexion = ConexionBD.getConexion(); // Establecer conexión al inicio
        if (conexion == null) {
            JOptionPane.showMessageDialog(this, "Error: No se pudo conectar a la base de datos.", "Error de conexión", JOptionPane.ERROR_MESSAGE);
            
        }
    }

    public static void main(String[] args) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla ().setVisible(true);
            }
        });
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombre_usuario = new javax.swing.JTextField();
        jLabel_Dueño = new javax.swing.JLabel();
        txt_cedula_usuario = new javax.swing.JTextField();
        jLabel_Cedula = new javax.swing.JLabel();
        txt_nombre_caballo = new javax.swing.JTextField();
        jLabel_Caballo = new javax.swing.JLabel();
        jLabel_Edad = new javax.swing.JLabel();
        jLabel_Afeccion = new javax.swing.JLabel();
        btn_eliminar_caballo = new javax.swing.JButton();
        btn_guardar_dieta = new javax.swing.JButton();
        btn_mostra_guardado = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_dieta = new javax.swing.JTable();
        txt_codigo_cabalo = new javax.swing.JTextField();
        idcaballojLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dietas para Equinos");
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 809, 500));
        setMaximumSize(new java.awt.Dimension(809, 500));
        setMinimumSize(new java.awt.Dimension(931, 553));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre_usuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 30));

        jLabel_Dueño.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel_Dueño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Dueño.setText("Nombre del Dueño");
        getContentPane().add(jLabel_Dueño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_cedula_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_cedula_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cedula_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cedula_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 140, 30));

        jLabel_Cedula.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel_Cedula.setText("C.C");
        getContentPane().add(jLabel_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        txt_nombre_caballo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nombre_caballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombre_caballoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombre_caballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, 30));

        jLabel_Caballo.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel_Caballo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Caballo.setText("Nombre del Equino");
        getContentPane().add(jLabel_Caballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel_Edad.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel_Edad.setText("Edad del equino");
        getContentPane().add(jLabel_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, -1, -1));

        jLabel_Afeccion.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel_Afeccion.setText("Estado de salud");
        getContentPane().add(jLabel_Afeccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, -1, -1));

        btn_eliminar_caballo.setText("Eliminar caballo");
        btn_eliminar_caballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminar_caballoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar_caballo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        btn_guardar_dieta.setText("Guardar y mostrar dietas");
        btn_guardar_dieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardar_dietaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardar_dieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        btn_mostra_guardado.setText("Registro");
        btn_mostra_guardado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostra_guardadoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mostra_guardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jLabel_Titulo.setBackground(new java.awt.Color(51, 255, 0));
        jLabel_Titulo.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel_Titulo.setText("DIETAS PRA EQUINOS");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        tbl_dieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "C.C", "Dueño", "Id Equino", "Equino", "Alimento", "Caracteristica", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_dieta.setMinimumSize(new java.awt.Dimension(80, 150));
        jScrollPane1.setViewportView(tbl_dieta);
        if (tbl_dieta.getColumnModel().getColumnCount() > 0) {
            tbl_dieta.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbl_dieta.getColumnModel().getColumn(5).setPreferredWidth(200);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 650, 280));
        getContentPane().add(txt_codigo_cabalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 110, 30));

        idcaballojLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        idcaballojLabel1.setText("Id Caballo");
        getContentPane().add(idcaballojLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salud optima", "Deshidratacion", "Desnutricion", "Parasitos" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Potro joven: 1 - 2 años", "Adolecente: 2-4 años", "Mayor: 4-15 años" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 ///////////////////////7
    private void limpiarCampos() {
        txt_nombre_usuario.setText("");
        txt_cedula_usuario.setText("");
        txt_nombre_caballo.setText("");
        txt_codigo_cabalo.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
    }
//////////////////////////
    private void txt_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_usuarioActionPerformed

    private void txt_cedula_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cedula_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cedula_usuarioActionPerformed

    private void txt_nombre_caballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombre_caballoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombre_caballoActionPerformed

    private void btn_guardar_dietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardar_dietaActionPerformed
String nombreDueño = txt_nombre_usuario.getText().trim();
String cedulaDueño = txt_cedula_usuario.getText().trim();
String nombreCaballo = txt_nombre_caballo.getText().trim();
String codigoCaballo = txt_codigo_cabalo.getText().trim();
String edad = (String) jComboBox2.getSelectedItem();
String afeccion = (String) jComboBox1.getSelectedItem();

if (nombreDueño.isEmpty() || cedulaDueño.isEmpty() || nombreCaballo.isEmpty() || codigoCaballo.isEmpty()
        || edad == null || edad.isEmpty() || afeccion == null || afeccion.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos y seleccione edad y estado de salud.", "Error",
    JOptionPane.ERROR_MESSAGE);
    return;
}

Gestion_cabalo gestion = new Gestion_cabalo(conexion);
gestion.guardarCaballoYDietas(nombreDueño, cedulaDueño, nombreCaballo, codigoCaballo, edad, afeccion);

int idCaballo = gestion.obtenerUltimoCaballoPorCodigo(codigoCaballo);
if (idCaballo != -1) {
    gestion.mostrarDietasEnTabla(tbl_dieta, idCaballo);
}
limpiarCampos();
    }//GEN-LAST:event_btn_guardar_dietaActionPerformed

    private void btn_mostra_guardadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostra_guardadoActionPerformed
Gestion_cabalo gestion = new Gestion_cabalo(conexion);
String[] dueños = gestion.obtenerListaDueños();
if (dueños.length == 0) {
    JOptionPane.showMessageDialog(this, "No hay dueños registrados.");
    return;
}

String dueñoSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione un dueño:", "Dueños",
                                    JOptionPane.PLAIN_MESSAGE, null, dueños, dueños[0]);
if (dueñoSeleccionado == null) return;
String cedulaDueño = dueñoSeleccionado.split(" - ")[0];

String[] caballos = gestion.obtenerListaCaballosPorCedula(cedulaDueño);
if (caballos.length == 0) {
    JOptionPane.showMessageDialog(this, "Este dueño no tiene caballos registrados.");
    return;
}

String caballoSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione un caballo:", "Caballos", 
                                      JOptionPane.PLAIN_MESSAGE, null, caballos, caballos[0]);
if (caballoSeleccionado == null) return;
int idCaballo = Integer.parseInt(caballoSeleccionado.split(" - ")[0]);

gestion.mostrarDietasEnTabla(tbl_dieta, idCaballo);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mostra_guardadoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btn_eliminar_caballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminar_caballoActionPerformed
  Gestion_cabalo gestion = new Gestion_cabalo(conexion);
String[] dueños = gestion.obtenerListaDueños();
if (dueños.length == 0) {
    JOptionPane.showMessageDialog(this, "No hay dueños registrados.");
    return;
}

String dueñoSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione un dueño:", "Eliminar caballo - Dueño",
                                    JOptionPane.PLAIN_MESSAGE, null, dueños, dueños[0]);
if (dueñoSeleccionado == null) return;
String cedulaDueño = dueñoSeleccionado.split(" - ")[0];

String[] caballos = gestion.obtenerListaCaballosPorCedula(cedulaDueño);
if (caballos.length == 0) {
    JOptionPane.showMessageDialog(this, "Este dueño no tiene caballos registrados.");
    return;
}
String caballoSeleccionado = (String) JOptionPane.showInputDialog(this, "Seleccione el caballo a eliminar:", "Eliminar caballo", 
                                      JOptionPane.PLAIN_MESSAGE, null, caballos, caballos[0]);
if (caballoSeleccionado == null) return;
int idCaballo = Integer.parseInt(caballoSeleccionado.split(" - ")[0]);

int confirm = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este caballo?", "Confirmación", JOptionPane.YES_NO_OPTION);
if (confirm == JOptionPane.YES_OPTION) {
    boolean eliminado = gestion.eliminarCaballoPorId(idCaballo);
    if (eliminado) {
        JOptionPane.showMessageDialog(this, "Caballo eliminado correctamente.");
        ((DefaultTableModel) tbl_dieta.getModel()).setRowCount(0);
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo eliminar el caballo.");
    }
}        // TODO add your handling code here:private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    }//GEN-LAST:event_btn_eliminar_caballoActionPerformed
   


////////////////////////////////
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar_caballo;
    private javax.swing.JButton btn_guardar_dieta;
    private javax.swing.JButton btn_mostra_guardado;
    private javax.swing.JLabel idcaballojLabel1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel_Afeccion;
    private javax.swing.JLabel jLabel_Caballo;
    private javax.swing.JLabel jLabel_Cedula;
    private javax.swing.JLabel jLabel_Dueño;
    private javax.swing.JLabel jLabel_Edad;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_dieta;
    private javax.swing.JTextField txt_cedula_usuario;
    private javax.swing.JTextField txt_codigo_cabalo;
    private javax.swing.JTextField txt_nombre_caballo;
    private javax.swing.JTextField txt_nombre_usuario;
    // End of variables declaration//GEN-END:variables
}



